import {foodProvider} from './foods.js';
import {dateKey,slots,minutes,nutrition,totals,dueItems} from './core.js';
const $=s=>document.querySelector(s), KEY='viva.v1';
const initial=()=>({version:1,settings:{wake:'07:00',end:'22:00',glass:200},days:{},supplements:[],body:[],customFoods:[]});
let state=initial(), storageBroken=false;
try{const raw=localStorage.getItem(KEY);if(raw){const value=JSON.parse(raw);if(value.version!==1||!value.settings||!value.days||!Array.isArray(value.body)||!Array.isArray(value.supplements))throw Error('Formato non valido');state=value}}catch{storageBroken=true;$('#storageError').hidden=false;$('#storageError').textContent='Archivio non leggibile. I dati esistenti non verranno sovrascritti; le nuove modifiche restano solo in questa sessione.'}
let selected=dateKey(), tab='today', audio=null, editId=null, searchVersion=0, lastToday=dateKey();
const fmt=n=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function save(){if(storageBroken)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{$('#storageError').hidden=false;$('#storageError').textContent='Salvataggio non riuscito: spazio esaurito o archiviazione bloccata. Le ultime modifiche restano solo in questa sessione.'}}
function fresh(){return {...state.settings,water:{},coffee:[],meals:[],routine:state.supplements.map(s=>({...s})),taken:{},notified:{}}}
function day(d=selected){return state.days[d]||fresh()}
function writable(d=selected){return state.days[d]||(state.days[d]=fresh())}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500)}
function macro(n){return `<div class="stats"><div><strong>${fmt(n.protein)} g</strong><span>Proteine</span></div><div><strong>${fmt(n.carbs)} g</strong><span>Carboidrati</span></div><div><strong>${fmt(n.fat)} g</strong><span>Grassi</span></div></div>`}
const empty=t=>`<div class="empty">${t}</div>`;
function render(){const d=day(), ts=slots(d.wake,d.end), count=ts.filter(t=>d.water[t]).length,n=totals(d.meals);$('#date').value=selected;$('#date').max=dateKey();$('#title').textContent=({today:'La tua giornata',water:'Un sorso alla volta',meals:'Il diario dei pasti',supplements:'La tua routine',body:'Il tuo percorso'})[tab];document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false')});const content=$('#view');
if(tab==='today'){const last=state.body.filter(b=>b.date<=selected).sort((a,b)=>b.date.localeCompare(a.date))[0];content.innerHTML=`<div class="grid"><section class="card feature"><div class="section-head"><h2>💧 Acqua</h2><span>${esc(d.wake)} – ${esc(d.end)}</span></div><div class="large">${count}<small> / ${ts.length} bicchieri</small></div><p class="muted">${fmt(count*d.glass/1000)} litri registrati · ${d.glass} ml a bicchiere</p><div class="progress"><i style="width:${count/ts.length*100}%"></i></div><button data-action="nextWater">${count===ts.length?'Routine completata ✓':'+ Ho bevuto un bicchiere'}</button></section><section class="card"><div class="section-head"><h2>◒ Alimentazione</h2><button data-go="meals">Aggiungi</button></div><div class="large">${fmt(n.kcal)}<small> kcal</small></div>${macro(n)}<p class="muted">${d.meals.length} alimenti nel diario di oggi</p></section>${coffeeCard(d)}<section class="card"><div class="section-head"><h2>✚ Integratori</h2><span class="pill">${d.routine.filter(s=>d.taken[s.id]).length} / ${d.routine.length}</span></div>${routine(d)}<button class="link" data-go="supplements">Gestisci routine →</button></section><section class="card"><div class="section-head"><h2>♡ Biometria</h2><button data-go="body">Registra</button></div>${last?`<div class="large">${fmt(last.weight)}<small> kg</small></div><p class="muted">Ultima misurazione · ${prettyDate(last.date)}</p><div class="stats"><div><strong>${last.fat===null?'—':fmt(last.fat)+'%'}</strong><span>Massa grassa</span></div><div><strong>${last.lean===null?'—':fmt(last.lean)+' kg'}</strong><span>Massa magra</span></div></div>`:empty('Il tuo percorso inizia da una misurazione. Registra peso e composizione corporea.')}</section></div>`}
if(tab==='water')content.innerHTML=`<section class="card"><div class="section-head"><h2>💧 ${count} di ${ts.length} bicchieri</h2><button data-action="settings">Orari</button></div><p class="muted">${fmt(count*d.glass/1000)} L registrati · un bicchiere da ${d.glass} ml ogni ora. Tocca per segnare o annullare.</p><div class="slots">${ts.map(t=>`<label class="slot ${d.water[t]?'done':''}"><input type="checkbox" data-water="${t}" ${d.water[t]?'checked':''}><strong>${t}</strong><small>${d.water[t]?'Bevuto ✓':d.glass+' ml'}</small></label>`).join('')}</div><p class="muted">Il conteggio deriva dagli orari scelti; non è un obiettivo medico personalizzato. Per lo storico, cambia la data in alto.</p></section>`;
if(tab==='meals'){content.innerHTML=`<div class="grid"><section class="card"><h2>Aggiungi un alimento</h2><form id="mealForm" class="stack"><label>Pasto<select name="meal"><option>Colazione</option><option>Pranzo</option><option>Cena</option><option>Spuntini</option></select></label><label>Cerca nel database<input id="foodSearch" type="search" placeholder="Es. riso, yogurt, pollo" autocomplete="off"></label><label>Alimento<select id="foodSelect" name="food" required></select></label><p class="muted" id="foodInfo"></p><p class="muted" id="foodSource"></p><label>Quantità (g)<input name="grams" id="grams" type="number" min="0.1" max="5000" step="0.1" value="100" required></label><p id="mealPreview" class="muted" aria-live="polite"></p><button class="primary">Aggiungi al diario</button><p class="muted">Valori per 100 g di parte edibile. Scegli crudo/cotto e la marca corretta. Whey e Milk PRO da bere: aggiungi la tua variante dall’etichetta; non sono ancora preimpostati.</p></form>${customFoodForm()}</section><div class="stack"><section class="card"><h2>Totale giornaliero</h2><div class="large">${fmt(n.kcal)}<small> kcal</small></div>${macro(n)}</section>${['Colazione','Pranzo','Cena','Spuntini'].map(type=>`<section class="card"><h3>${type}</h3>${d.meals.filter(m=>m.meal===type).map(m=>`<div class="row"><div class="detail"><strong>${esc(m.food.name)}</strong><small>${fmt(m.grams)} g · ${fmt(nutrition(m.food,m.grams).kcal)} kcal</small></div><button data-delete-meal="${m.id}" aria-label="Elimina ${esc(m.food.name)}">✕</button></div>`).join('')||empty('Nessun alimento registrato.')}</section>`).join('')}</div></div>`;populateFoods();$('#foodSearch').addEventListener('input',populateFoods);$('#foodSelect').addEventListener('change',previewFood);$('#grams').addEventListener('input',previewFood);$('#mealForm').addEventListener('submit',addMeal);$('#customFoodForm').addEventListener('submit',addCustomFood)}
if(tab==='supplements'){const s=state.supplements.find(s=>s.id===editId);content.innerHTML=`<div class="grid"><div class="stack"><section class="card"><h2>Da assumere · ${prettyDate(selected)}</h2>${routine(d)||empty('Nessun integratore previsto.')}</section><section class="card"><h2>I tuoi integratori</h2><p class="muted">Inseriscili una sola volta: si ripetono automaticamente ogni giorno, anche per 3 mesi o più, finché non li modifichi o elimini. Ogni giorno devi solo spuntare «assunto». Le modifiche aggiornano oggi e i prossimi giorni; lo storico già registrato conserva la routine originale.</p>${state.supplements.map(s=>`<div class="row"><div class="detail"><strong>${esc(s.name)}</strong><small>${esc(s.time)} · ${esc(s.dose)}</small></div><button data-edit-supp="${s.id}">Modifica</button><button class="danger" data-delete-supp="${s.id}">Elimina</button></div>`).join('')||empty('Aggiungi il primo integratore.')}</section></div><section class="card"><h2>${s?'Modifica integratore':'Nuovo integratore'}</h2><p class="muted">Ripetizione: ogni giorno · senza scadenza</p><form id="suppForm" class="stack"><label>Nome<input name="name" maxlength="80" value="${esc(s?.name||'')}" required></label><label>Dose / note<input name="dose" maxlength="160" value="${esc(s?.dose||'')}" placeholder="Es. 1 capsula dopo colazione"></label><label>Orario<input name="time" type="time" value="${s?.time||'08:00'}" required></label><button class="primary">${s?'Salva modifiche':'Aggiungi integratore'}</button>${s?'<button type="button" data-action="cancelEdit">Annulla</button>':''}</form></section></div>`;$('#suppForm').addEventListener('submit',saveSupplement)}
if(tab==='body'){const record=state.body.find(b=>b.date===selected);content.innerHTML=`<div class="grid"><section class="card"><h2>Registra una misurazione</h2><p class="muted">Una misurazione per data. Salvando una data già presente la aggiorni.</p><form id="bodyForm" class="form-grid"><label class="full">Data<input name="date" type="date" max="${dateKey()}" value="${selected}" required></label><label>Peso (kg)<input name="weight" type="number" min="1" max="500" step="0.1" value="${record?.weight||''}" required></label><label>Massa grassa (%)<input name="fat" type="number" min="0" max="100" step="0.1" value="${record?.fat??''}"></label><label>Massa magra (kg)<input name="lean" type="number" min="0" max="500" step="0.1" value="${record?.lean??''}"></label><p class="muted">Massa grassa e massa magra sono facoltative; inserisci i valori misurati.</p><button class="primary full">Salva misurazione</button></form></section><section class="card"><h2>Storico misurazioni</h2>${[...state.body].sort((a,b)=>b.date.localeCompare(a.date)).map(b=>`<div class="row"><div class="detail"><strong>${fmt(b.weight)} kg <small>· ${prettyDate(b.date)}</small></strong><small>Grassa ${b.fat===null?'—':fmt(b.fat)+'%'} · Magra ${b.lean===null?'—':fmt(b.lean)+' kg'}</small></div><button data-edit-body="${b.date}">Modifica</button><button data-delete-body="${b.date}" aria-label="Elimina misurazione del ${b.date}">✕</button></div>`).join('')||empty('Le tue misurazioni appariranno qui.')}</section></div>`;$('#bodyForm').addEventListener('submit',saveBody)}
const coffeeForm=$('#coffeeForm');if(coffeeForm)coffeeForm.addEventListener('submit',addCoffee);
renderReminders();}
function coffeeCard(d){const entries=d.coffee||[];const now=new Date();const time=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;return `<section class="card"><div class="section-head"><h2>☕ Caffè</h2><span class="pill">${entries.length} registrati</span></div><form id="coffeeForm"><label>Orario del caffè<input name="time" type="time" value="${time}" required></label><button class="primary">+ Ho preso un caffè</button></form><p class="muted">Registrato nella data selezionata. Il conteggio non aggiunge calorie: latte e zucchero vanno inseriti nei pasti.</p>${entries.slice().sort((a,b)=>a.time.localeCompare(b.time)).map(c=>`<div class="row"><div class="detail"><strong>☕ Caffè · ${esc(c.time)}</strong></div><button data-delete-coffee="${esc(c.id)}" aria-label="Elimina caffè delle ${esc(c.time)}">✕</button></div>`).join('')||empty('Nessun caffè registrato in questa giornata.')}</section>`}
function addCoffee(e){e.preventDefault();const time=new FormData(e.target).get('time');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))return;const d=writable();d.coffee ||= [];d.coffee.push({id:uid(),time});save();render();toast('Caffè registrato')}
function prettyDate(value){return new Date(value+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short',year:'numeric'})}
function routine(d){return d.routine.length?d.routine.slice().sort((a,b)=>a.time.localeCompare(b.time)).map(s=>`<label class="row"><input type="checkbox" data-taken="${s.id}" ${d.taken[s.id]?'checked':''}><span class="detail"><strong>${esc(s.name)}</strong><small>${esc(s.time)} · ${esc(s.dose)||'Nessuna nota'}${d.taken[s.id]?' · Assunto':''}</small></span></label>`).join(''):empty('Nessun integratore in programma.')}
function customFoodForm(){return `<hr><details><summary>Aggiungi un alimento personale</summary><p class="muted">Salvalo una volta e lo ritroverai nella ricerca. Copia i valori per 100 g dall’etichetta: il nome da solo non permette di calcolarli automaticamente.</p><form id="customFoodForm" class="form-grid"><label class="full">Nome e marca / preparazione<input name="name" maxlength="120" placeholder="Es. Yogurt bianco · marca" required></label>${[['kcal','Calorie (kcal)',900],['protein','Proteine (g)',100],['carbs','Carboidrati (g)',100],['fat','Grassi (g)',100]].map(([key,label,max])=>`<label>${label} per 100 g<input name="${key}" type="number" min="0" max="${max}" step="0.01" required></label>`).join('')}<button class="primary full">Salva nel mio database</button></form></details><p class="muted">${(state.customFoods||[]).length} alimenti personali salvati su questo dispositivo.</p>`}
function addCustomFood(e){e.preventDefault();const data=new FormData(e.target),name=data.get('name').trim();if(!name){toast('Inserisci il nome dell’alimento');return}const food={id:'custom-'+uid(),name};for(const k of ['kcal','protein','carbs','fat']){food[k]=Number(data.get(k));if(data.get(k)===''||!Number.isFinite(food[k])||food[k]<0||food[k]>(k==='kcal'?900:100)){toast('Controlla i valori per 100 g');return}}state.customFoods ||= [];if(state.customFoods.some(f=>f.name.toLocaleLowerCase('it')===name.toLocaleLowerCase('it'))){toast('Nome già presente: specifica marca o variante');return}state.customFoods.push(food);save();render();toast('Alimento salvato: lo trovi nella ricerca')}
async function populateFoods(){const version=++searchVersion;try{const list=await foodProvider.search($('#foodSearch').value,state.customFoods||[]);if(version!==searchVersion||tab!=='meals')return;$('#foodSelect').innerHTML=list.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('')||'<option value="">Nessun alimento trovato</option>';await previewFood()}catch{toast('Database alimenti non disponibile. Riprova.')}}
async function previewFood(){const id=$('#foodSelect')?.value, f=await foodProvider.get(id,state.customFoods||[]);if(tab!=='meals'||$('#foodSelect').value!==id)return;$('#foodInfo').textContent=f?`Per 100 g: ${fmt(f.kcal)} kcal · P ${fmt(f.protein)} g · C ${fmt(f.carbs)} g · G ${fmt(f.fat)} g`:'';const source=$('#foodSource');source.replaceChildren();if(f?.note)source.append(document.createTextNode(f.note+' '));if(f?.source&&/^https:\/\//.test(f.source)){const a=document.createElement('a');a.href=f.source;a.textContent='Fonte: '+(f.sourceLabel||'Scheda nutrizionale');a.target='_blank';a.rel='noopener noreferrer';source.append(a)}else if(f)source.textContent=f.id.startsWith('custom-')?'Valori inseriti da te.':'Voce del catalogo iniziale: valori indicativi.';const g=Number($('#grams').value),n=f&&nutrition(f,g);$('#mealPreview').textContent=n&&g>0?`Questa porzione: ${fmt(n.kcal)} kcal · P ${fmt(n.protein)} g · C ${fmt(n.carbs)} g · G ${fmt(n.fat)} g`:''}
async function addMeal(e){e.preventDefault();const data=new FormData(e.target),g=Number(data.get('grams')),mealDate=selected;const f=await foodProvider.get(data.get('food'),state.customFoods||[]);if(!f||!Number.isFinite(g)||g<=0||g>5000)return;writable(mealDate).meals.push({id:uid(),meal:data.get('meal'),grams:g,food:{...f}});save();render();toast('Alimento aggiunto')}
function syncRoutine(){const d=writable(dateKey());d.routine=state.supplements.map(s=>({...s}))}
function saveSupplement(e){e.preventDefault();const data=new FormData(e.target);const name=data.get('name').trim();if(!name){toast('Inserisci un nome');return}const s={id:editId||uid(),name,dose:data.get('dose').trim(),time:data.get('time')};if(editId)state.supplements=state.supplements.map(x=>x.id===editId?s:x);else state.supplements.push(s);editId=null;syncRoutine();save();render();toast('Routine aggiornata')}
function saveBody(e){e.preventDefault();const data=new FormData(e.target),weight=Number(data.get('weight')),fat=data.get('fat')===''?null:Number(data.get('fat')),lean=data.get('lean')===''?null:Number(data.get('lean'));if(lean!==null&&lean>weight){toast('La massa magra non può superare il peso');return}const entry={date:data.get('date'),weight,fat,lean};state.body=state.body.filter(b=>b.date!==entry.date);state.body.push(entry);save();render();toast('Misurazione salvata')}
function openSettings(){const f=$('#settingsForm');for(const k of ['wake','end','glass'])f.elements[k].value=state.settings[k];$('#settings').showModal();notificationStatus()}
$('#settingsButton').onclick=openSettings;$('#closeSettings').onclick=()=>$('#settings').close();
$('#settingsForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),wake=data.get('wake'),end=data.get('end');if(minutes(end)<minutes(wake)){toast('La fine giornata deve essere successiva alla sveglia');return}const glass=Number(data.get('glass'));state.settings={wake,end,glass};const d=writable(dateKey());Object.assign(d,state.settings);save();$('#settings').close();render();toast('Orari aggiornati')};
$('#date').onchange=e=>{if(!e.target.value||e.target.value>dateKey()){e.target.value=selected;return}selected=e.target.value;editId=null;render()};
document.addEventListener('change',e=>{const water=e.target.dataset.water,taken=e.target.dataset.taken;if(water)writable().water[water]=e.target.checked;if(taken)writable().taken[taken]=e.target.checked;if(water||taken){save();render()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset;
if(a.tab||a.go){tab=a.tab||a.go;editId=null;render();window.scrollTo(0,0)}
if(a.action==='settings')openSettings();
if(a.action==='nextWater'){const d=day(),t=slots(d.wake,d.end).find(t=>!d.water[t]);if(t){writable().water[t]=true;save();render();toast('Bicchiere registrato')}}
if(a.deleteCoffee){writable().coffee=(day().coffee||[]).filter(c=>c.id!==a.deleteCoffee);save();render();toast('Caffè rimosso')}
if(a.deleteMeal){writable().meals=day().meals.filter(m=>m.id!==a.deleteMeal);save();render()}
if(a.editSupp){editId=a.editSupp;render();$('#suppForm input').focus()}
if(a.action==='cancelEdit'){editId=null;render()}
if(a.deleteSupp&&confirm('Eliminare questo integratore dalla routine? Lo storico precedente resta disponibile.')){state.supplements=state.supplements.filter(s=>s.id!==a.deleteSupp);editId=null;syncRoutine();save();render()}
if(a.deleteBody&&confirm('Eliminare questa misurazione?')){state.body=state.body.filter(b=>b.date!==a.deleteBody);save();render()}
if(a.editBody){selected=a.editBody;render();$('#bodyForm input').focus()}
});
function renderReminders(){const pending=dueItems(day(dateKey()),new Date());$('#reminders').innerHTML=pending.length?`<div class="warning"><div><strong>Oggi: ${pending.length} attività da segnare</strong><br><small>${pending.slice(0,2).map(x=>esc(x.label)).join(' · ')}${pending.length>2?' …':''}</small></div><button data-action="showPending">Apri</button></div>`:''}
document.addEventListener('click',e=>{if(e.target.closest('[data-action="showPending"]')){selected=dateKey();tab='today';render()}});
async function beep(){try{if(!audio)return;await audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=660;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.15,audio.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.45);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.5)}catch{toast('Suono non disponibile su questo browser')}}
$('#sound').onclick=async()=>{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){toast('Suono non supportato');return}audio ||= new Audio();await beep();$('#sound').textContent='Suono attivo · Prova ancora'};
function notificationStatus(){const n=$('#notificationStatus');n.textContent=!('Notification'in window)?'Notifiche di sistema non disponibili in questo browser. Avvisi visivi sempre attivi.':`Permesso notifiche: ${{granted:'concesso',denied:'negato: modifica le impostazioni del browser',default:'non richiesto'}[Notification.permission]}. Gli avvisi programmati funzionano solo ad app aperta.`}
$('#notifications').onclick=async()=>{if(!('Notification'in window)){notificationStatus();return}try{await Notification.requestPermission();notificationStatus();if(Notification.permission==='granted')await notify('Avvisi abilitati','Promemoria disponibili mentre Viva è aperta.')}catch{toast('Notifiche non disponibili: usa gli avvisi nell’app')}};
async function notify(title,body){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker?.getRegistration();if(reg)await reg.showNotification(title,{body,icon:'icons/icon-192.png',tag:'viva-reminder'});else new Notification(title,{body})}catch{/* Il riepilogo visivo resta sempre disponibile. */}}
function tick(){const today=dateKey();if(today!==lastToday){if(selected===lastToday)selected=today;lastToday=today;render()}if(document.visibilityState!=='visible')return;const now=new Date(),d=day(today),pending=dueItems(d,now);renderReminders();const current=pending.filter(x=>minutes(x.time)===now.getHours()*60+now.getMinutes()&&!d.notified[x.key]);if(current.length){const active=writable(today);for(const x of current)active.notified[x.key]=true;save();const msg=current.map(x=>x.label).join(' · ');toast(msg);beep();notify('È il momento della tua routine',msg)}}
if('serviceWorker'in navigator&&window.isSecureContext){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#offlineStatus').textContent='Modalità offline pronta dopo il primo caricamento completo.'}).catch(()=>{$('#offlineStatus').textContent='Modalità offline non disponibile. Usa HTTPS o localhost.'})}else $('#offlineStatus').textContent='Per installazione e offline, apri l’app tramite HTTPS (o localhost sul computer).';
render();tick();setInterval(tick,15000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')tick()});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const updated=JSON.parse(e.newValue);if(updated.version===1){state=updated;render()}}catch{}}});
