// Catalogo nutrizionale pubblico. Nessun dato personale o dosaggio dei PDF.
export const planFoods = [
  {
    "id": "crea-007000",
    "name": "Albicocche, fresche",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007000",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 42.0,
    "protein": 0.4,
    "fat": 0.1,
    "carbs": 9.8,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-004010",
    "name": "Ceci in scatola, scolati",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/004010",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 111.0,
    "protein": 6.7,
    "fat": 2.3,
    "carbs": 13.9,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007710",
    "name": "Ciliegie, fresche",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007710",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 48.0,
    "protein": 0.8,
    "fat": 0.1,
    "carbs": 11.0,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000045",
    "name": "Cous cous, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000045",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 361.0,
    "protein": 13.7,
    "fat": 1.1,
    "carbs": 76.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000046",
    "name": "Cous cous, cotto",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000046",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 179.0,
    "protein": 3.6,
    "fat": 1.1,
    "carbs": 39.7,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000020",
    "name": "Farro perlato, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000020",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 353.0,
    "protein": 14.6,
    "fat": 2.4,
    "carbs": 69.3,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000025",
    "name": "Farro perlato, cotto bollito",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000025",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 178.0,
    "protein": 6.2,
    "fat": 1.0,
    "carbs": 37.3,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007730",
    "name": "Fragole, fresche",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007730",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 30.0,
    "protein": 0.9,
    "fat": 0.4,
    "carbs": 5.3,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-005410",
    "name": "Lattuga, cruda",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/005410",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 22.0,
    "protein": 1.8,
    "fat": 0.4,
    "carbs": 2.2,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007230",
    "name": "Melone estivo, senza buccia",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007230",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 34.0,
    "protein": 0.8,
    "fat": 0.2,
    "carbs": 7.4,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-121410",
    "name": "Merluzzo o nasello, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/121410",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 71.0,
    "protein": 17.0,
    "fat": 0.3,
    "carbs": 0.0,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007760",
    "name": "Mirtilli, freschi",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007760",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 49.0,
    "protein": 0.9,
    "fat": 0.2,
    "carbs": 10.1,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-121730",
    "name": "Orata di allevamento, filetto crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/121730",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 159.0,
    "protein": 19.7,
    "fat": 8.4,
    "carbs": 1.2,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-005600",
    "name": "Peperoni, crudi",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/005600",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 26.0,
    "protein": 0.9,
    "fat": 0.3,
    "carbs": 4.2,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007290",
    "name": "Pesche, con buccia",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007290",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 28.0,
    "protein": 0.7,
    "fat": 0,
    "carbs": 5.8,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007340",
    "name": "Susine / prugne, fresche",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007340",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 45.0,
    "protein": 0.5,
    "fat": 0.1,
    "carbs": 10.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-166820",
    "name": "Ricotta vaccina",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/166820",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 146.0,
    "protein": 8.8,
    "fat": 10.9,
    "carbs": 3.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000130",
    "name": "Riso basmati, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000130",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 367.0,
    "protein": 9.0,
    "fat": 1.9,
    "carbs": 82.9,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000135",
    "name": "Riso basmati, cotto bollito",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000135",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 113.0,
    "protein": 3.0,
    "fat": 0.6,
    "carbs": 25.2,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000110",
    "name": "Riso integrale, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000110",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 341.0,
    "protein": 7.5,
    "fat": 1.9,
    "carbs": 77.4,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-000115",
    "name": "Riso integrale, cotto bollito",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/000115",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 113.0,
    "protein": 2.5,
    "fat": 0.6,
    "carbs": 25.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-166850",
    "name": "Robiola",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/166850",
    "sourceLabel": "CREA",
    "note": "Voce generica CREA; le robiole fresche confezionate possono avere valori diversi. Verifica l’etichetta.",
    "kcal": 338.0,
    "protein": 20.0,
    "fat": 27.7,
    "carbs": 2.3,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-005700",
    "name": "Spinaci, crudi",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/005700",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 35.0,
    "protein": 3.4,
    "fat": 0.7,
    "carbs": 2.9,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-005705",
    "name": "Spinaci, cotti bolliti",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/005705",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 41.0,
    "protein": 4.0,
    "fat": 0.8,
    "carbs": 3.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-182010",
    "name": "Albume di uovo, crudo",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/182010",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 43.0,
    "protein": 10.7,
    "fat": 0,
    "carbs": 0,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-007380",
    "name": "Uva, fresca",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/007380",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 64.0,
    "protein": 0.5,
    "fat": 0.1,
    "carbs": 15.6,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-004130",
    "name": "Fagioli borlotti in scatola, scolati",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/004130",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 102.0,
    "protein": 6.7,
    "fat": 0.5,
    "carbs": 15.9,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-004210",
    "name": "Fagioli cannellini in scatola, scolati",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/004210",
    "sourceLabel": "CREA",
    "note": "Valori medi per 100 g di parte edibile; condimenti esclusi.",
    "kcal": 86.0,
    "protein": 6.0,
    "fat": 0.6,
    "carbs": 12.5,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-170010",
    "name": "Fiocchi di latte / formaggio magro, generici",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/170010",
    "sourceLabel": "CREA",
    "note": "Valore medio CREA: non è l’etichetta Naturella.",
    "kcal": 115.0,
    "protein": 9.7,
    "fat": 7.1,
    "carbs": 3.2,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "crea-123010",
    "name": "Sgombro in salamoia, sgocciolato",
    "source": "https://www.alimentinutrizione.it/tabelle-nutrizionali/123010",
    "sourceLabel": "CREA",
    "note": "Solo prodotto in salamoia, sgocciolato; non usare per sgombro sott’olio.",
    "kcal": 177.0,
    "protein": 19.3,
    "fat": 11.1,
    "carbs": 0.0,
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "fage-total-0",
    "name": "Yogurt FAGE Total bianco 0%",
    "kcal": 54,
    "protein": 10.3,
    "carbs": 3,
    "fat": 0,
    "source": "https://it.fage/prodotti/yogurt-bianco/fage-total-0",
    "sourceLabel": "FAGE",
    "note": "Solo Total bianco 0%, non versioni alla frutta. Verifica l’etichetta attuale.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "wasa-integrale",
    "name": "Wasa Integrale di segale",
    "kcal": 338,
    "protein": 9,
    "carbs": 62,
    "fat": 1.5,
    "source": "https://www.wasa.com/it-it/prodotti/integrale/",
    "sourceLabel": "Wasa",
    "note": "Pesa le fette: la scheda attuale indica circa 9 g per fetta, non 20 g.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "more-fresche",
    "name": "More, fresche",
    "kcal": 36,
    "protein": 1.39,
    "carbs": 9.61,
    "fat": 0.49,
    "source": "https://www.humanitas.it/enciclopedia/alimenti/frutta/more/",
    "sourceLabel": "Humanitas",
    "note": "Valori come riportati dalla fonte; carboidrati totali comprensivi di fibra (5,3 g/100 g), diversamente dai carboidrati disponibili CREA.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "lindt-90",
    "name": "Cioccolato fondente 90% · Lindt Excellence",
    "kcal": 592,
    "protein": 10,
    "carbs": 14,
    "fat": 55,
    "source": "https://www.lindt.it/tavoletta-excellence-90-100g",
    "sourceLabel": "Lindt",
    "note": "Variante di riferimento: il piano non specifica la marca. Usa questi valori solo per questo prodotto.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "milk-kefir-bio",
    "name": "Kefir bianco naturale da bere BIO · Milk",
    "kcal": 44,
    "protein": 3.5,
    "carbs": 4,
    "fat": 1.5,
    "source": "https://www.my-milk.it/prodotti/kefir-e-latte-fermentato/kefir-50.html",
    "sourceLabel": "Milk",
    "note": "Variante di riferimento da 480 g: il piano non specifica il kefir. Non è Milk PRO High Protein.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "roast-beef-tallone",
    "name": "Roast beef cotto · Tallone",
    "kcal": 139,
    "protein": 20.7,
    "carbs": 0,
    "fat": 6.2,
    "source": "https://www.tallonesnc.com/schede-tecniche-prodotti/roast-beef.pdf",
    "sourceLabel": "Tallone",
    "note": "Preparazione di riferimento: il piano non specifica la marca. Altre ricette possono avere valori diversi.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "naturella-pro",
    "name": "Fiocchi di latte PRO Naturella",
    "kcal": 87,
    "protein": 12,
    "carbs": 3,
    "fat": 3,
    "source": "https://shop.despar.com/spesa-consegna-domicilio/87100/prodotto/naturella-fiocchi-di-latte-pro-naturella-200-g-1349100",
    "sourceLabel": "Etichetta su Despar",
    "note": "Versione PRO da 200 g. Il piano non specifica la versione: verifica che la tua confezione riporti questi valori.",
    "verifiedOn": "2026-09-22"
  },
  {
    "id": "fage-total-5",
    "name": "Yogurt greco bianco 5% · FAGE Total",
    "kcal": 93,
    "protein": 9,
    "carbs": 3,
    "fat": 5,
    "source": "https://it.fage/prodotti/fage-total-5/fage-total-5-450g",
    "sourceLabel": "FAGE",
    "note": "Valori per 100 g di FAGE Total bianco 5%. Per altre marche verifica l’etichetta.",
    "verifiedOn": "2026-09-23"
  },
  {
    "id": "mevgal-greek-10",
    "name": "Yogurt greco bianco 10% · MEVGAL",
    "kcal": 129,
    "protein": 5.5,
    "carbs": 3.5,
    "fat": 10,
    "source": "https://www.odysea.com/product/mevgal-greek-yoghurt-cows-milk-500g/",
    "sourceLabel": "MEVGAL 500 g · scheda Odysea",
    "note": "Valori per 100 g della variante MEVGAL 10% da 500 g nella scheda Odysea. Formulazioni e mercati possono differire: confronta la confezione.",
    "verifiedOn": "2026-09-23"
  }
];
